feat(pacmak): retry select external command invocations
aws/jsii pull request #2013
Opened 2020-09-15 09:35 UTC by RomainMuller

When generating packages, `jsii-pacmak` will defer to external tools for
compilation (`dotnet`, `mvn`, `pip`, ...). Those commands will typically
require some kind of network transfer (e.g: to resolve dependencies from
their standard package registry), which is susceptible to fail (due to
poor network conditions, getting throttled in CI/CD, etc...).

In order to reduce the likelihood that such failures will interrupt the
user workflow abruptly (forcing a manual retry, and possibly breaking
CI/CD workflows), back-off and retries will be performed when these
commands fail (up to 5 tentatives in total, with exponential back-off
using a 150ms base cooldown and a factor of 2).

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2020-09-15 09:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 8d274736e5d2674b88042044df3f06d76fddca7b
* Result: FAILED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6dfd17bd-b574-4b4d-9852-8f0999f5bf7a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-15 09:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 88cd919693509d3039f1c7aee1da95ad3366626a
* Result: FAILED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ba45cc9f-c817-4cd0-8489-21a77f618feb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-15 10:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 67b4736ff81e3ca425314f71cacd25d42aded2b3
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=76aabee9-e2ff-47f0-9b1d-3169b2076177%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-15 10:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: a4cb50e775b1d466b86b1f938308c4eeb93f9810
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e4f6feaa-6958-4d77-9996-c140feb04eca%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-16 08:42 UTC, rix0rrr requested changes
Why did the retry mechanism need to be rewritten instead of simply turned on?

2020-09-16 08:42 UTC, rix0rrr commented on packages/jsii-pacmak/lib/util.ts
> +  maxTries?: number;
`maxAttempts` then? This word grates on me for some reason.

2020-09-16 09:10 UTC, RomainMuller commented
For some reason I only noticed there was already support for retries **after** writing the new retry wrapper. And the old retry mechanism lacked support for back-off, making it questionnable for working around throttles / DDOS protections.

2020-09-16 09:27 UTC, rix0rrr approved these changes

2020-09-16 09:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 962a1427e4031b554e7d77aa93c1f802fdc7d4c7
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9f0a5277-3733-44f9-a96d-dc928e5a987b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-16 10:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 2352134c5ddd4690d7f10ffd33125d7271ef8bd8
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bf43c07e-ed9d-46f0-a37b-8d6c64ef3351%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-16 11:25 UTC, merged