chore: generate module embedding
aws/jsii pull request #2041
Opened 2020-09-23 23:35 UTC by SoManyHs

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2020-09-23 23:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: bd846ad8f243dd589178f49d46b87401579aadd7
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c9c868e9-9709-49e5-8515-c0fcea4f87e1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-24 14:36 UTC, RomainMuller commented on packages/jsii-pacmak/lib/targets/go.ts
> +import * as path from 'path';
May I be so bold as to ask we sort those imports (external / not-starting with `.` first, then internal / starting with `.`)?

2020-09-24 14:36 UTC, RomainMuller commented on packages/jsii-pacmak/lib/targets/go.ts
> +    this.code.openFile(bundledRuntimeDotGo);
This file was opened, but never closed... Perhaps this explains why it does not show in the output?

2020-09-24 14:47 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: aca444792197ff556cef4eb9389e8da708f762f3
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7c9b19ad-1270-4ac4-b54c-aabb50655344%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-24 16:35 UTC, MrArnoldPalmer requested changes

2020-09-24 16:35 UTC, MrArnoldPalmer commented on packages/jsii-pacmak/lib/targets/go.ts
> +    this.code.openFile(bundledRuntimeDotGo);
These two lines aren't doing anything, they can be removed.

2020-09-24 18:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 8cfc3d2354b75b3645ad329ab68f63b4ae17a7b1
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0ad4afcf-3ea1-463e-9722-f7ec0e877d9b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-24 18:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 23d86c920da7b74c607f3bcaba1ad2b5f7d9f510
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=de87cc0c-0430-41b7-af7d-e54c31f9152f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-24 21:13 UTC, MrArnoldPalmer approved these changes
👏

2020-09-24 21:14 UTC, merged