fix(go): fix generation of readonly and static properties
aws/jsii pull request #2133
Opened 2020-10-15 21:03 UTC by SoManyHs

Previously, we were generating setters for readonly properties, as well as including static properties as part of a class interface and implementation. This fixes the property generation to omit the setter declarations/implementations for readonly properties. It also generates static properties as the package level.

Fixes #2093
---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2020-10-15 21:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 4917d346119c96a789d1cf9c4f98a71f0b3ca8e5
* Result: FAILED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9951dfa6-cbc4-49de-84d6-5187bd14ffae%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-15 21:09 UTC, SoManyHs commented
Note: It maybe worth considering refactoring this so that the static properties are wrapped in a `StaticProperty` class and then have a list `StaticProperty[]` as a member on the GoClass as we do with `staticMethods`; however, I wanted to wait until the StaticGet jsii call is implemented before doing so. I tried a few ways of having a `StaticProperty` class extend from existing classes, but none of the abstractions seemed to quite fit so simply made a `emitStaticProperty` private method on the class instead of following the usual `SomeConstruct.emit()` pattern.

2020-10-15 21:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: ec8d416bdb526f053bfeef438a306043c4facf0c
* Result: FAILED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b50224c2-46aa-44d5-8e10-970d4e98e624%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-15 21:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 6cc1347384aea5e7313776915cb66f63f524fd6c
* Result: FAILED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e3fc2ad7-57ec-41f8-acfc-b7db80adc401%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-15 22:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 60ff599c671855710597beb22f29df2c2e8f3c97
* Result: FAILED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0e09c9e9-4ee6-42ff-98f3-c54ee69fd487%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-15 23:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 6d889b357b676c2580cea520435180bf601535fc
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=db825fdb-e904-4c3e-a084-e2053e2d25a8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-16 08:00 UTC, RomainMuller requested changes

2020-10-16 19:55 UTC, MrArnoldPalmer commented
> _NOTE_: It maybe worth considering refactoring this so that the static properties are wrapped in a `StaticProperty` class and then have a list `StaticProperty[]` as a member on the GoClass as we do with `staticMethods`; however, I wanted to wait until the StaticGet jsii call is implemented before doing so. I tried a few ways of having a `StaticProperty` class extend from existing classes, but none of the abstractions seemed to quite fit so simply made a `emitStaticProperty` private method on the class instead of following the usual `SomeConstruct.emit()` pattern. @MrArnoldPalmer

I think this is the right way to go. That would also remove the need for these checks
```
   for (const prop of this.properties) {
      if (prop.static) {
        // emit static get
...
```
```
    for (const property of this.properties) {
      if (!property.static) {
        // emit non-static get
...
```

There isn't a lot of shared behavior between static and non-static property getters so a common ancestor wouldn't have much.  Basically the only common thing it needs is the stuff declared on the `GoTypeMember` + the `immutable` property.

This could warrant an abstract wrapper class, or maybe just another interface like
```
interface GoPropertyMember extends GoTypeMember {
  immutable: boolean
}
```

Since they would take the same constructor args maybe an abstract class is best.

2020-10-16 20:58 UTC, SoManyHs commented on packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
> +      return;
whoops, that was just a copy-pasta oversight. will fix.

2020-10-16 21:05 UTC, SoManyHs commented on packages/jsii-pacmak/lib/targets/go/types/type-member.ts
> +      const instanceArg = receiver.substring(0, 1).toLowerCase();
In go we usually use the single variable, yes. Not really the concept of "self" since Go isn't OO.

2020-10-17 04:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 7be3ed97c3d80435a281366afa63ecad02f39bee
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=73ebf36f-c50b-4058-890a-e51eea6b8eab%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-17 04:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 27be7e492a8ae3d39d05f3d6321c1607ae6db28b
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=05c61c9a-cd45-4c49-b437-63eece8fa0fd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-17 04:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 02a283512f3b01440b3b7378b815ec8d7575d7b0
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0723e0d8-24b1-4b90-93e6-56efec233c7b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-19 10:06 UTC, RomainMuller approved these changes

2020-10-19 10:07 UTC, RomainMuller commented
Added `pr/do-not-merge` if you wanna take the refactor route in this PR (I'm cool if you prefer to do it separately, too - in which case just drop the label or have @MrArnoldPalmer  drop it).

2020-10-19 10:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 7a5bde606525314ede981b23d90b61cbb6c54492
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=77e42c09-4594-44d2-a049-4fb0a875faba%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-20 00:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 5256973853c32cdf2f80fd9bcdb7233ab45c383d
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3ef8c9f3-fe12-4407-b209-e828e67c53e2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-20 03:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 7e23f5998551c5bc830b37e27baddb988574b4b4
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=32fa6b12-8d27-4175-ac93-0f02638f857a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-20 08:12 UTC, RomainMuller submitted a review, later dismissed

2020-10-20 22:18 UTC, SoManyHs commented
@mergifyio update

2020-10-20 22:33 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 0911eb579c474c19d2b5e9f1667ba873526120b6
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5399a322-3b4e-4634-bc27-52ff0a03692b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-20 23:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 4144adee53140c215aa37c2907da73ff024cdb7a
* Result: FAILED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e08d3852-225b-4466-ab01-28e3c6d649f7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-21 06:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 25d351c40df08e12d894c03dc0e176f5143725f1
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=563dba9a-a1ce-488e-b8cc-e67ce5a5f0ff%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-21 07:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-Blkkw9bQFn8A
* Commit ID: 9560eb12b02a2e92039971e6f95c8d9768c4e622
* Result: SUCCEEDED
* [Build Logs](https://d445wms7qi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0faca385-c4c2-4d5b-b33d-c3f691e135b8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-21 07:50 UTC, SoManyHs commented
@Mergifyio update

2020-10-21 08:30 UTC, RomainMuller approved these changes

2020-10-21 08:31 UTC, RomainMuller commented
@MergifyIO refresh

2020-10-21 08:31 UTC, merged