chore: generate go.mod files
aws/jsii pull request #2265
Opened 2020-11-19 06:05 UTC by SoManyHs

Closes #2090

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2020-11-19 06:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: d1b30b4f720672b488e73b6bbe187744971bf8e5
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ee6cb0ac-83b2-4132-bea8-4d6542f25aa5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-19 06:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: ba6c92c46cbe6856de52cc986180c70860cb5c79
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0976dd63-e17b-406d-beb1-042d01da214f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-19 06:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: 9485d2510cb437b0e0306b6cdbac6cc9678d96ec
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8540ac34-ac02-4484-94a6-f8e191477507%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-19 06:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: a61358bd4c9a358cafda8861839db6d642906b4d
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7a37e5c9-041d-4556-a876-c57465505671%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-19 06:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: 69297b58aafe1d53b5643909dbbbf2ba6187e0e6
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b4e3ff99-adc0-4998-b60c-fdab5b64c3d8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-19 07:32 UTC, MrArnoldPalmer requested changes

2020-11-19 07:32 UTC, MrArnoldPalmer commented on packages/jsii-pacmak/lib/targets/go/package.ts
> +        code.line(`${packageName}`);
we should include versions for each dependency as well.

2020-11-19 07:32 UTC, MrArnoldPalmer commented on packages/jsii-pacmak/lib/targets/go/package.ts
> +      for (const packageName of this.dependencyImports) {
We also need to declare a dependency on the jsii runtime module. the version of this dependency should be available in the package assembly under `jsiiVersion`.

2020-11-19 17:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: 47e712ddb2434041669c1c9a08816baff7910570
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ac1ad6d8-c858-4178-9b1a-4b8b728ce612%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-19 19:12 UTC, MrArnoldPalmer requested changes

2020-11-19 19:12 UTC, MrArnoldPalmer commented on packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
> +	_jsii_ "github.com/aws-cdk/jsii/jsii-experimental"
What is the module alias here? I haven't seen it in go.mod before.

Jsii runtime should also be versioned to the jsiiVerion provided in the assembly.

2020-11-19 19:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: f42e56eb837b931f3b6271e292afd1cd7db149cd
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b22ba8dc-b84e-4bd2-9186-6a12b9842aab%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-19 19:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: 6a91f96041e7a63be1488c9408ba7883f2d171f3
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9a5b218d-80b8-4111-8ff2-2fede6220c6f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-19 20:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: a1ad9c59b3f40ef029983fc540c3d68ead8f4b0c
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d89f7e97-dce1-4794-bf51-7db8a05dd6b4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-19 22:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: 6a91f96041e7a63be1488c9408ba7883f2d171f3
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5ccc54c2-e0f2-43c5-b96d-7275e68aaa95%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-19 23:02 UTC, MrArnoldPalmer approved these changes

2020-11-19 23:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: 0dfaf7a68eaa64b962c78f3c9bc4b81782ba4604
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8cd5dc24-727d-4b00-9ccf-76e634f04832%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-20 04:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: 23dd96604dcf38730c0c4993adc82344f632ffb9
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e50afc84-f85b-4dd2-b8b1-584058498670%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-20 05:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: 2961a3d2ebb445bd6f8ca872630cbea5e89d1525
* Result: FAILED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cdea536f-c403-406b-b2a6-da73198a4ee2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-20 05:14 UTC, MrArnoldPalmer approved these changes

2020-11-20 05:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-5lHf64IXfvmr
* Commit ID: 05bb727abf6f0ec77a2d06e066efd1fe20457dfc
* Result: SUCCEEDED
* [Build Logs](https://2syhly7xq4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ff49ac84-6448-4eec-998b-758884755d7f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-20 09:14 UTC, RomainMuller approved these changes

2020-11-20 09:15 UTC, merged