feat: add support for using default .m2 when packaging Java
aws/jsii pull request #3573
Opened 2022-06-04 01:55 UTC by agdimech

The existing Java packaging process uses a localRepository which points to a newly created tmp directory. This means that when building, all dependencies need to be freshly downloaded which is contributing a significant portion of time to the packaging process.

This PR provides the option to the user (hidden) to use their existing .m2 default repository if they so choose. I have experienced a huge improvement to performance by enabling this setting (5s with enabled vs 4 minutes using defaults).

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2022-06-04 01:56 UTC, agdimech commented on packages/jsii-pacmak/bin/jsii-pacmak.ts
> +      default: false,
I have set the default to `false` for this setting to maintain backward compatibility. I am wandering whether this should be defaulted to `true` in future as I am not sure what negative side effects there would be by using the user's .m2 repository.

2022-06-07 08:05 UTC, RomainMuller commented
We moved away from the default cache locations for both .NET and Java because this had surprising consequences due to how both will always prefer artifacts already in cache (which is good), AND store the outputs of local builds into this cache (which is where surprises come from).

I reckon the performance improvement you see comes from not re-downloading dependencies on each build... which is also achieved when using a non-default, but also non-transient cache. Maybe the right think is to allow configuring a specific `.m2` directory (which could be the default one, if that is what the user wants). This would be more flexible and also feels safer...

2022-06-08 08:23 UTC, RomainMuller requested changes

2022-06-08 08:24 UTC, RomainMuller commented
Can you perhaps also see to _use_ that configuration flag somewhere (e.g: in one of the flavors of the build test, perhaps)?

2022-06-09 04:42 UTC, agdimech commented on packages/jsii-pacmak/lib/targets/java.ts
> +              this.options.arguments['java-custom-cache-path'] ??
Fixed.

2022-06-09 04:42 UTC, agdimech commented on packages/jsii-pacmak/bin/jsii-pacmak.ts
> +    .option('java-custom-cache-path', {
Fixed.

2022-06-13 13:45 UTC, RomainMuller approved these changes

2022-06-13 15:24 UTC, merged